import {
  HomeOutlined, LineChartOutlined, WalletOutlined, MessageOutlined,
  FundOutlined, SettingOutlined, ApiOutlined, BellOutlined,
  FileTextOutlined, DatabaseOutlined, BookOutlined, SolutionOutlined,
  SafetyCertificateOutlined, TeamOutlined, SafetyOutlined, MenuOutlined,
  UserOutlined, FolderOutlined, FileOutlined, BarcodeOutlined,
  LinkOutlined, PlusOutlined, EditOutlined, DeleteOutlined,
  SearchOutlined, ReloadOutlined, DownloadOutlined, UploadOutlined,
  EyeOutlined, EyeInvisibleOutlined, LockOutlined,
  ClockCircleOutlined, InboxOutlined, SendOutlined,
  AppstoreOutlined, BarsOutlined, DashboardOutlined,
  KeyOutlined, ProfileOutlined, BlockOutlined,
  ToolOutlined, FlagOutlined, StarOutlined,
  ThunderboltOutlined, CloudOutlined, NodeIndexOutlined,
  HeartOutlined, SmileOutlined, RocketOutlined,
  CheckCircleOutlined, CloseCircleOutlined, InfoCircleOutlined,
  QuestionCircleOutlined, ExclamationCircleOutlined,
  ShoppingCartOutlined, TagOutlined, TableOutlined,
  ColumnWidthOutlined, ColumnHeightOutlined, RiseOutlined,
  FallOutlined, StockOutlined, AreaChartOutlined,
  BarChartOutlined, PieChartOutlined, DotChartOutlined,
  RadarChartOutlined, HeatMapOutlined, MailOutlined,
  PhoneOutlined, NotificationOutlined, SoundOutlined,
  BulbOutlined, ExperimentOutlined, EnvironmentOutlined,
  PushpinOutlined, PaperClipOutlined, UnorderedListOutlined,
  NumberOutlined, CheckOutlined, CloseOutlined,
  PoweroffOutlined, LoginOutlined, LogoutOutlined,
  SwapOutlined, ShakeOutlined, VerticalAlignMiddleOutlined,
  MinusOutlined, EllipsisOutlined,
  FullscreenOutlined, FullscreenExitOutlined,
  GithubOutlined, GlobalOutlined, ReloadOutlined as RedoOutlined
} from '@ant-design/icons-vue'

export const iconMap = {
  HomeOutlined, LineChartOutlined, WalletOutlined, MessageOutlined,
  FundOutlined, SettingOutlined, ApiOutlined, BellOutlined,
  FileTextOutlined, DatabaseOutlined, BookOutlined, SolutionOutlined,
  SafetyCertificateOutlined, TeamOutlined, SafetyOutlined, MenuOutlined,
  UserOutlined, FolderOutlined, FileOutlined, BarcodeOutlined,
  LinkOutlined, PlusOutlined, EditOutlined, DeleteOutlined,
  SearchOutlined, ReloadOutlined, DownloadOutlined, UploadOutlined,
  EyeOutlined, EyeInvisibleOutlined, LockOutlined,
  ClockCircleOutlined, InboxOutlined, SendOutlined,
  AppstoreOutlined, BarsOutlined, DashboardOutlined,
  KeyOutlined, ProfileOutlined, BlockOutlined,
  ToolOutlined, FlagOutlined, StarOutlined,
  ThunderboltOutlined, CloudOutlined, NodeIndexOutlined,
  HeartOutlined, SmileOutlined, RocketOutlined,
  CheckCircleOutlined, CloseCircleOutlined, InfoCircleOutlined,
  QuestionCircleOutlined, ExclamationCircleOutlined,
  ShoppingCartOutlined, TagOutlined, TableOutlined,
  ColumnWidthOutlined, ColumnHeightOutlined, RiseOutlined,
  FallOutlined, StockOutlined, AreaChartOutlined,
  BarChartOutlined, PieChartOutlined, DotChartOutlined,
  RadarChartOutlined, HeatMapOutlined, MailOutlined,
  PhoneOutlined, NotificationOutlined, SoundOutlined,
  BulbOutlined, ExperimentOutlined, EnvironmentOutlined,
  PushpinOutlined, PaperClipOutlined, UnorderedListOutlined,
  NumberOutlined, CheckOutlined, CloseOutlined,
  PoweroffOutlined, LoginOutlined, LogoutOutlined,
  SwapOutlined, ShakeOutlined, VerticalAlignMiddleOutlined,
  MinusOutlined, EllipsisOutlined,
  FullscreenOutlined, FullscreenExitOutlined,
  GithubOutlined, GlobalOutlined, RedoOutlined
}

export function resolveIcon(name) {
  return iconMap[name] || null
}
