import {
    ApiOutlined,
    AppstoreOutlined,
    AreaChartOutlined,
    BarChartOutlined,
    BarcodeOutlined,
    BarsOutlined,
    BellOutlined,
    BlockOutlined,
    BookOutlined,
    BulbOutlined,
    CheckCircleOutlined,
    CheckOutlined,
    ClockCircleOutlined,
    CloseCircleOutlined,
    CloseOutlined,
    CloudOutlined,
    ColumnHeightOutlined,
    ColumnWidthOutlined,
    DashboardOutlined,
    DatabaseOutlined,
    DeleteOutlined,
    DotChartOutlined,
    DownloadOutlined,
    EditOutlined,
    EllipsisOutlined,
    EnvironmentOutlined,
    ExclamationCircleOutlined,
    ExperimentOutlined,
    EyeInvisibleOutlined,
    EyeOutlined,
    FallOutlined,
    FileOutlined,
    FileTextOutlined,
    FlagOutlined,
    FolderOutlined,
    FullscreenExitOutlined,
    FullscreenOutlined,
    FundOutlined,
    GithubOutlined,
    GlobalOutlined,
    HeartOutlined,
    HeatMapOutlined,
    HomeOutlined,
    InboxOutlined,
    InfoCircleOutlined,
    KeyOutlined,
    LineChartOutlined,
    LinkOutlined,
    LockOutlined,
    LoginOutlined,
    LogoutOutlined,
    MailOutlined,
    MenuOutlined,
    MessageOutlined,
    MinusOutlined,
    NodeIndexOutlined,
    NotificationOutlined,
    NumberOutlined,
    PaperClipOutlined,
    PhoneOutlined,
    PieChartOutlined,
    PlusOutlined,
    PoweroffOutlined,
    ProfileOutlined,
    PushpinOutlined,
    QuestionCircleOutlined,
    RadarChartOutlined,
    ReloadOutlined,
    ReloadOutlined as RedoOutlined,
    RiseOutlined,
    RocketOutlined,
    SafetyCertificateOutlined,
    SafetyOutlined,
    SearchOutlined,
    SendOutlined,
    SettingOutlined,
    ShakeOutlined,
    ShoppingCartOutlined,
    SmileOutlined,
    SolutionOutlined,
    SoundOutlined,
    StarOutlined,
    StockOutlined,
    SwapOutlined,
    TableOutlined,
    TagOutlined,
    TeamOutlined,
    ThunderboltOutlined,
    ToolOutlined,
    UnorderedListOutlined,
    UploadOutlined,
    UserOutlined,
    VerticalAlignMiddleOutlined,
    WalletOutlined
} from '@ant-design/icons-vue'

export const iconMap = {
  HomeOutlined, LineChartOutlined, WalletOutlined, MessageOutlined,
  FundOutlined, SettingOutlined, ApiOutlined, BellOutlined,
  FileTextOutlined, DatabaseOutlined, BookOutlined, SolutionOutlined,
  SafetyCertificateOutlined, TeamOutlined, SafetyOutlined, MenuOutlined,
  UserOutlined, FolderOutlined, FileOutlined, BarcodeOutlined,
  LinkOutlined, PlusOutlined, EditOutlined, DeleteOutlined,
  SearchOutlined, ReloadOutlined, DownloadOutlined, UploadOutlined,
  EyeOutlined, EyeInvisibleOutlined, LockOutlined,
  ClockCircleOutlined, InboxOutlined, SendOutlined,
  AppstoreOutlined, BarsOutlined, DashboardOutlined,
  KeyOutlined, ProfileOutlined, BlockOutlined,
  ToolOutlined, FlagOutlined, StarOutlined,
  ThunderboltOutlined, CloudOutlined, NodeIndexOutlined,
  HeartOutlined, SmileOutlined, RocketOutlined,
  CheckCircleOutlined, CloseCircleOutlined, InfoCircleOutlined,
  QuestionCircleOutlined, ExclamationCircleOutlined,
  ShoppingCartOutlined, TagOutlined, TableOutlined,
  ColumnWidthOutlined, ColumnHeightOutlined, RiseOutlined,
  FallOutlined, StockOutlined, AreaChartOutlined,
  BarChartOutlined, PieChartOutlined, DotChartOutlined,
  RadarChartOutlined, HeatMapOutlined, MailOutlined,
  PhoneOutlined, NotificationOutlined, SoundOutlined,
  BulbOutlined, ExperimentOutlined, EnvironmentOutlined,
  PushpinOutlined, PaperClipOutlined, UnorderedListOutlined,
  NumberOutlined, CheckOutlined, CloseOutlined,
  PoweroffOutlined, LoginOutlined, LogoutOutlined,
  SwapOutlined, ShakeOutlined, VerticalAlignMiddleOutlined,
  MinusOutlined, EllipsisOutlined,
  FullscreenOutlined, FullscreenExitOutlined,
  GithubOutlined, GlobalOutlined, RedoOutlined
}

export function resolveIcon(name) {
  return iconMap[name] || null
}
